logging:
  level:
    org.springframework: ${LOG_LEVEL:INFO}
    com.javatmp: DEBUG


spring.batch.job.enabled: false
#spring:
#  batch:
#    job:
#      name: job2
spring:
  batch:
    jdbc:
      initialize-schema: always

#spring.datasource.url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;LOCK_MODE=3
spring.datasource.url: jdbc:h2:file:d:/batchdb;DB_CLOSE_DELAY=-1;LOCK_MODE=3

#spring.datasource.url: jdbc:h2:file:./batchdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;LOCK_MODE=3
#spring.datasource.url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
#  ;NON_KEYWORDS=USER

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/batchdb

#spring.datasource.driver-class-name: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password:
