
spring.batch.job.enabled: false
#spring:
#  batch:
#    job:
#      name: job2
spring.datasource.url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
#  ;NON_KEYWORDS=USER

#spring.datasource.driver-class-name: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password:
