application:
  message: "Welcome To local property from config server"

spring:
  application:
    name: cloud-service-empty
  config:
    import: optional:configserver:${spring.cloud.config.uri}
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8071
    circuitbreaker:
      bulkhead:
        resilience4j:
          enabled: false # https://docs.spring.io/spring-cloud-circuitbreaker/reference/spring-cloud-circuitbreaker-resilience4j/bulkhead-pattern-supporting.html

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 10
  retry:
    instances:
      RetryService:
        max-attempts: 3
        wait-duration: 1s
  bulkhead:
    instances:
      BulkheadService:
        max-concurrent-calls: 3
        max-wait-duration: 1
  ratelimiter:
    instances:
      RateLimiterService:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
