app:
  message: Message has been sent Successfully..
spring:
  rabbitmq:
    host: localhost
    password: password
    port: 15672
    username: user
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey
server:
  port: 9091
